apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  ports:
    - port: 5432
  selector:
    tier: postgresql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: postgresql
    spec:
      containers:
      - image: postgres:14.4
        name: postgresql
        env:
        - name: POSTGRES_USER
          value: "$PGUSER"
        - name: POSTGRES_PASSWORD
          value: "$PGPASS"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc